apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: git-storage
  name: git-storage
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
