apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: registry-claim
  name: registry-claim
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
